### ISSUE TITLE
Unexpected token u when creating a vmss

### ISSUE THREAD

**Issue by jluk** [sauryadas/Azure-CLI-VMSS#30] opened 2016-03-18 23:06 UTC
@huangpf can you please help me?

I am attempting to create a vmss, however I am hitting this error.

1) Run 'azure vmss create-or-update -g simpleQT2 -n vmsstest'

Results are:

```
info:    Executing command vmss create-or-update
error:   Unexpected token u
info:    Error information has been recorded to C:\Users\JULUK\.azure\azure.err
error:   vmss create-or-update command failed
```

Error stack trace:

```
2016-03-18T23:01:34.860Z:
{ [SyntaxError: Unexpected token u]
  stack: [Getter/Setter],
  __frame: undefined,
  rawStack: [Getter] }
SyntaxError: Unexpected token u
  <<< async stack >>>
    at Object.parse (native)
    at __1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:209:34)
  <<< raw stack >>>
    at Object.parse (native)
    at __$__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:209:34)
    at __$__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:197:164)
    at __$__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:197:180)
    at __$__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:192:203)
    at __$__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:192:219)
    at __func (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\streamline\lib\callbacks\runtime.js:47:5)
    at AzureCli.__1 (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\commands\arm\compute\compute.js:182:786)
    at AzureCli.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\lib\cli.js:228:12)
    at AzureCli.<anonymous> (C:\Program Files (x86)\Microsoft SDKs\Azure\CLI\node_modules\commander\lib\commander.js:235:8)
```

**Comment by huangpf** [comment] 2016-03-18 23:14
@jluk 
Please try `azure vmss` and `azure vmssvm` to see all the current commands.

Then
`azure vmss create-or-update -h` to see the help.

**Comment by gatneil** [comment] 2016-03-18 23:17
He tried to run the command below; it should either prompt for more options or successfully create a vmss; it shoult not error (the current behavior)

'azure vmss create-or-update -g simpleQT2 -n vmsstest'

**Comment by huangpf** [comment] 2016-03-18 23:51
@gatneil @jluk sorry -- I was looking at a wrong place in the GitHub email.

It seems like a bug that it shall prompt from parameters input, i.e. `-p` or `--parameter-file``.

For now, you have to include either of these 2 for making the command call.

**Comment by huangpf** [comment] 2016-03-18 23:55
Sample:

```
azure vmss config generate --parameter-file .\vmss.json
azure vmss config -h
azure vmss config XXX ... // config the parameter file by command, or manually via text editor
azure vmss create-or-update -g a -n a --parameter-file .\vmss.json
```

**Comment by gatneil** [comment] 2016-03-22 02:36
@huangpf Makes sense; is this something that will be fixed eventually?

**Comment by gatneil** [comment] 2016-03-22 02:45
@huangpf Also, even if I supply the -p option, it still doesn't prompt me for parameters; it just says "argument missing" (screenshot below); it should instead prompot me for parameters

![capture](https://cloud.githubusercontent.com/assets/1448593/13940729/5996157c-ef9d-11e5-8af4-23c2e93d0720.PNG)

**Comment by huangpf** [comment] 2016-03-22 03:05
`-p` is not a switch parameter, so this is by design that it expects some input there.

I will try to fix the `--parameter-file` prompting issue.

**Closed as completed** 2019-10-02 16:23 UTC
Labels: P1
