### ISSUE TITLE
azure vmss quick-create ImageURN needs helpful printout

### ISSUE THREAD

**Issue by gatneil** [sauryadas/Azure-CLI-VMSS#40] opened 2016-03-22 02:58 UTC
If I'm trying to quick-create a vmss, I would have no idea what to specify for the ImageURN. (lots of internal people who use Azure still ask me how to find the list of images!). Can we add some printout that tells the user they can find the list of options by first doing 'azure vm image list-publishers' to find a publisher, then doing 'azure vm image list' with the publisher they want?

**Comment by sauryadas** [comment] 2016-03-22 03:11
@gatneil duplicate of #33

**Closed as completed by sauryadas** 2016-03-22 03:11 UTC
